import {prepareEvidence} from './prepare-evidence.js';
export function createEvidenceUI({getBoard,getTeam,getState,openModal,mutate,esc,toast,onDone}){
 const $=s=>document.querySelector(s);let running=false,controller;
 function open(){if(running){toast('A research queue is already running. Pause it before starting another.');return;}const b=getBoard(),team=getTeam()[0],scopeSignature=JSON.stringify({key:b.studio.scopeKey,from:b.studio.from,to:b.studio.to});let job=b.studio.jobs.evidence;
  openModal('Prepare APEX scores',`<div class="modal-body"><p>Pull advanced Baseball-Reference value, prepare role-aware performance scores, and keep every result editable.</p><p class="notice">Lore auto-fill is off. Add nicknames, moments, fan memories and non-player legends in the custom sections after the player board is built.</p><label class="bulk-option"><input id="evidence-lore" type="checkbox"> Include older story lookup anyway</label><label class="bulk-option"><input id="evidence-restart" type="checkbox"> Refresh every candidate, including previously processed names</label><div class="studio-actions"><button class="primary" id="evidence-start">${job&&job.cursor<job.ids.length?'Continue prep':'Prepare APEX scores'}</button><button id="evidence-stop" class="subtle" disabled>Pause</button></div><p id="evidence-status" role="status">${job?esc(job.message||'Queue saved.'):`${b.candidates.length} candidates. Keep this dialog open; progress saves after each person.`}</p><div id="evidence-review"></div><button id="evidence-rank" class="subtle">Review scoring & ranking</button></div>`,true);
  $('#evidence-stop').onclick=()=>controller?.abort();$('#evidence-rank').onclick=()=>{if(running){toast('Pause the queue first.');return;}$('#modal').close();onDone();};
  $('#evidence-start').onclick=async()=>{if(running)return;const includeLore=$('#evidence-lore').checked;if(!job||job.cursor>=job.ids.length||job.scopeSignature!==scopeSignature||job.includeLore!==includeLore||$('#evidence-restart').checked){job={scopeSignature,includeLore,ids:b.candidates.map(c=>c.id),cursor:0,review:[],message:''};mutate(()=>{b.studio.jobs.evidence=job;},null,{redraw:false});}const missed=job.ids.slice(0,job.cursor).filter(id=>b.candidates.find(c=>c.id===id)?.profile?.preparation?.issues?.some(x=>/429|cooling down/.test(x)));if(missed.length)job.ids.splice(job.cursor,0,...missed);controller=new AbortController();let rateLimits=0;running=true;$('#evidence-start').disabled=true;$('#evidence-stop').disabled=false;$('#evidence-lore').disabled=true;const close=()=>controller.abort();$('#modal').addEventListener('close',close,{once:true});
   try{for(;job.cursor<job.ids.length;){if(job.retryAt>Date.now())await waitForSource(job.retryAt,controller.signal,message=>{if($('#evidence-status'))$('#evidence-status').textContent=message;});if(controller.signal.aborted||getState().boards[team]!==b)break;const id=job.ids[job.cursor],c=b.candidates.find(x=>x.id===id);if(!c){job.cursor++;continue;}const stamp=JSON.stringify(c);let retryAfter=0;try{const next=await prepareEvidence(c,team,b.studio,{signal:controller.signal,includeLore,progress:message=>{if($('#evidence-status'))$('#evidence-status').textContent=`${job.cursor+1}/${job.ids.length} · ${c.name} · ${message}`;}});if(controller.signal.aborted)break;retryAfter=next.profile.preparation.retryAfter||0;const i=b.candidates.findIndex(x=>x.id===id);if(i<0||JSON.stringify(b.candidates[i])!==stamp){job.review.push({name:c.name,message:'Candidate changed during lookup; result was not applied.'});}else mutate(()=>{b.candidates[i]=next;for(const issue of next.profile.preparation.issues)job.review.push({name:c.name,message:issue});},null,{redraw:false});}catch(e){if(controller.signal.aborted)break;job.review.push({name:c.name,message:e.message});}if(retryAfter){job.retryAt=Date.now()+retryAfter*1000;mutate(()=>{},null,{redraw:false});rateLimits++;if(rateLimits>=2)break;continue;}job.retryAt=0;job.cursor++;job.message=`${job.cursor}/${job.ids.length} processed · ${job.review.length} review notes`;mutate(()=>{},null,{redraw:false});if($('#evidence-review'))$('#evidence-review').innerHTML=job.review.slice(-8).map(x=>`<p class="help">${esc(x.name)}: ${esc(x.message)}</p>`).join('');await waitForSource(Date.now()+1500,controller.signal);}
   }catch(e){if(e.name!=='AbortError')toast(e.message);}finally{running=false;job.message=`${job.cursor}/${job.ids.length} processed · ${job.review.length} review notes${job.cursor<job.ids.length?(job.retryAt>Date.now()?' · Source limited requests; progress saved. Continue later.':' · Paused'):''}`;mutate(()=>{},null,{redraw:false});if($('#evidence-status')){$('#evidence-status').textContent=job.message;$('#evidence-start').disabled=false;$('#evidence-stop').disabled=true;$('#evidence-lore').disabled=false;}$('#modal').removeEventListener('close',close);}}
 }
 return {open};
}

export async function waitForSource(until,signal,progress=()=>{}){
 while(Date.now()<until){if(signal?.aborted)throw new DOMException('Paused','AbortError');progress(`Biography source needs a break · retrying in ${Math.ceil((until-Date.now())/1000)} seconds. Progress is saved; you can pause.`);await new Promise(resolve=>{const done=()=>{clearTimeout(timer);signal?.removeEventListener('abort',done);resolve();};const timer=setTimeout(done,Math.min(1000,until-Date.now()));signal?.addEventListener('abort',done,{once:true});});}
 if(signal?.aborted)throw new DOMException('Paused','AbortError');
}
