import {applyAutoScores} from './legends.js';
import {newCandidate} from './model.js';
import {FRANCHISE_DATA,normalizedName,safeSourceURL,parseCandidateList,planListImport,parseReferenceTable,mlbSnapshots,appendSnapshots} from './data-import.js';

export function renderStatImports(c,esc,{compact=false,editable=false,collapsed=false}={}){
 const items=c.statImports||[];if(!items.length)return '';
 return `<section class="stat-imports"><div class="stat-imports-heading"><h3>Imported player data</h3><span>${items.length} saved ${items.length===1?'table':'tables'}</span></div>${items.map(s=>`<details class="stat-snapshot" ${compact||collapsed?'':'open'}><summary><span><strong>${esc(s.label)}</strong><small>${esc(s.provider)} · ${esc(s.scope)}</small></span></summary><div class="stat-snapshot-body">${s.summary.length?`<div class="stats-grid">${s.summary.map(x=>`<div><span>${esc(x.label)}</span><strong>${esc(x.value)}</strong></div>`).join('')}</div>`:''}${compact&&s.summary.length?'':tableHTML(s.columns,s.rows,esc)}<div class="stat-source"><span>Saved ${esc(new Date(s.importedAt).toLocaleDateString())}${s.url?` · <a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">View source ↗</a>`:''}</span>${editable?`<button type="button" class="danger-text" data-remove-stat="${esc(s.id)}">Remove table</button>`:''}</div>${s.provider==='MLB Stats API'?'<p class="help">Totals use the selected franchise seasons. Rate stats are recalculated from counts; missing values remain unavailable. MLB data courtesy of MLB Advanced Media.</p>':''}</div></details>`).join('')}</section>`;
}
function tableHTML(headers,rows,esc,selectable=null){return `<div class="data-table-wrap"><table class="data-table"><thead><tr>${selectable?'<th scope="col">Keep</th>':''}${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr>${selectable?`<td><input type="checkbox" data-keep-row="${i}" aria-label="Keep data row ${i+1}" ${selectable.includes(i)?'checked':''}></td>`:''}${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
export function createImportUI({getBoard,getTeam,openModal,mutate,toast,esc,download,lookupPlayers}){
 const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];let generation=0;
 const addSource=(c,url)=>{if(url&&!c.sources.includes(url))c.sources=[c.sources,url].filter(Boolean).join('\n');};
 function saveTables(name,tables,role=''){
  if(!name.trim())throw Error('Enter the player’s name.');if(name.trim().length>150)throw Error('Player names must be 150 characters or fewer.');
  const candidates=getBoard().candidates;const existing=candidates.find(c=>normalizedName(c.name)===normalizedName(name));
  if(existing&&existing.type!=='Player')throw Error('This name belongs to a non-player. Use a distinct player name.');
  if(!existing&&candidates.length>=1000)throw Error('This franchise already has 1,000 candidates.');
  let next=appendSnapshots(existing||newCandidate(name.trim()),tables);next.sample=false;if(!next.role&&role)next.role=role;for(const s of tables)addSource(next,s.url);if(getBoard().autoStats!==false)next=applyAutoScores(next);
  mutate(()=>{const i=getBoard().candidates.findIndex(c=>c.id===next.id);if(i<0)getBoard().candidates.push(next);else getBoard().candidates[i]=next;},`${tables.length} stat ${tables.length===1?'table':'tables'} saved for ${next.name}.`);$('#modal').close();
 }
 const yearFields=(from)=>`<div class="import-year-fields"><label>From season<input id="data-from" type="number" min="1800" max="2100" value="${from}" required></label><label>Through season<input id="data-to" type="number" min="1800" max="2100" value="${new Date().getFullYear()}" required></label></div>`;
 function years(){const from=Number($('#data-from').value),to=Number($('#data-to').value);if(!Number.isInteger(from)||!Number.isInteger(to)||from<1800||to>2100||from>to)throw Error('Enter a valid year range, from 1800 through 2100.');return [from,to];}
 const showError=(node,e)=>node.innerHTML=`<p class="error" role="alert">${esc(e.message||'Something went wrong. Please try again.')}</p>`;
 const fileBind=(fileId,textId,outId)=>{$(fileId).onchange=async e=>{const file=e.target.files[0],fileGeneration=generation;if(!file)return;try{if(file.size>2000000)throw Error('Choose a text file smaller than 2 MB.');const contents=await file.text();if(fileGeneration!==generation||!$(textId))return;$(textId).value=contents;$(outId).innerHTML='';}catch(err){if(fileGeneration===generation&&$(outId))showError($(outId),err);}};};
 const resetPreview=(form,preview)=>{$$(form+' input, '+form+' textarea').forEach(e=>e.addEventListener('input',()=>{$(preview).innerHTML='';}));};
 function openImport(which='list',prefill=''){
  const current=++generation;const [code,name]=getTeam();const config=FRANCHISE_DATA[code];
  openModal('Import & player data',`<div class="import-tabs" role="tablist" aria-label="Import method">${[['list','Candidate list'],['reference','Baseball-Reference'],['mlb','MLB lookup']].map(([id,label])=>`<button role="tab" aria-selected="${id===which}" class="${id===which?'active':''}" data-import-tab="${id}">${label}</button>`).join('')}</div><div class="modal-body import-body"><div class="import-destination"><span>DESTINATION</span><strong>${esc(name)}</strong><small>New names append to your candidate pool. Existing candidates keep their rankings and scores.</small></div><div id="import-content"></div></div>`,true);
  $$('[data-import-tab]').forEach(b=>b.onclick=()=>openImport(b.dataset.importTab,prefill));
  if(which==='list')listView();else if(which==='reference')referenceView(config,prefill);else mlbView(config,prefill,current);
 }
 function listView(){
  $('#import-content').innerHTML=`<h3>Bring in your candidate list</h3><p class="help">Paste a numbered list, CSV, tab-separated spreadsheet cells, or a Markdown table. A table needs a <strong>Name</strong> or <strong>Player</strong> column. Notes, nicknames, roles, and non-player types are recognized. Use full names.</p><form id="list-form"><label class="import-upload">Upload CSV, TSV, or text<input id="list-file" type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values,text/plain"></label><label>Or paste your list<textarea id="list-text" rows="8" placeholder="1. Paul O’Neill&#10;2. Johnny Bench&#10;3. Joe Morgan" required></textarea></label><label class="bulk-option"><input id="lookup-after-import" type="checkbox" checked> Automatically fetch MLB stats for new players</label><div class="import-action-row"><button class="primary">Preview import</button><button type="button" class="text-button" id="list-template">Download CSV template</button></div></form><div id="list-preview" aria-live="polite"></div>`;
  fileBind('#list-file','#list-text','#list-preview');resetPreview('#list-form','#list-preview');
  $('#list-template').onclick=()=>download('legacy-lore-candidate-template.csv','Name,Type,Nickname,Role,Era,Tier,Famous moments,Graphic Easter eggs,Research notes,Sources\r\nExample Player,Player,Nickname,Outfield,1980–1990,Candidate,Add a famous moment,Add a hidden detail,Add research notes,\r\nExample Broadcaster,Broadcaster,Signature call,Radio,1970–2000,Candidate,Add a memorable call,A microphone,Add research notes,\r\n','text/csv');
  $('#list-form').onsubmit=e=>{e.preventDefault();try{const {entries,warnings}=parseCandidateList($('#list-text').value);const plan=planListImport(entries,getBoard().candidates);$('#list-preview').innerHTML=`<div class="notice"><strong>${plan.added.length} new candidates · ${plan.skipped.length} existing names skipped</strong><p>Existing notes, scores, and order are preserved. Imported statistics or overall score columns are not converted into lore or FLS points.</p></div>${warnings.length?`<p class="help">${warnings.map(esc).join('<br>')}</p>`:''}${tableHTML(['Name','Type','Nickname','Status'],entries.map(c=>[c.name,c.type,c.nickname,plan.added.includes(c)?'Add to pool':'Already on board']),esc)}<button class="primary" id="apply-list-import" ${plan.added.length?'':'disabled'}>Import ${plan.added.length} candidates</button>`;$('#apply-list-import').onclick=()=>{const fresh=planListImport(entries,getBoard().candidates);const lookup=$('#lookup-after-import').checked;mutate(()=>getBoard().candidates.push(...fresh.added),`${fresh.added.length} candidates imported.`);$('#modal').close();const players=fresh.added.filter(c=>c.type==='Player').map(c=>c.id);if(lookup&&players.length&&lookupPlayers)lookupPlayers(players);};}catch(err){showError($('#list-preview'),err);}};
 }
 function referenceView(config,prefill){
  $('#import-content').innerHTML=`<h3>Import a Baseball-Reference table</h3><p class="help">On Baseball-Reference, use the table’s <strong>Share & Export → Get table as CSV</strong>, then paste it here. You can also copy a table from a spreadsheet. Automatic scraping is not used. <a href="https://www.sports-reference.com/blog/2016/11/exporting-data/" target="_blank" rel="noopener noreferrer">Export help ↗</a></p><form id="reference-form"><div class="form-grid"><label>Player name<input id="reference-name" list="existing-players" value="${esc(prefill)}" required maxlength="150" placeholder="Paul O’Neill"></label><label>Table title<input id="reference-title" value="Franchise stats" required maxlength="200"></label></div><datalist id="existing-players">${getBoard().candidates.filter(c=>c.type==='Player').map(c=>`<option value="${esc(c.name)}">`).join('')}</datalist><label>Baseball-Reference source URL (optional)<input id="reference-url" type="url" placeholder="https://www.baseball-reference.com/players/…"></label><div class="reference-filters"><label>Franchise team codes (comma separated)<input id="reference-aliases" value="${esc(config[1])}" required></label>${yearFields(config[2])}</div><p class="help">Review the team codes and years to match your franchise scope. Matching season rows are selected first; career and multi-team totals are excluded when team/year columns identify them.</p><label class="import-upload">Upload CSV, TSV, or text<input id="reference-file" type="file" accept=".csv,.tsv,.txt,text/csv,text/plain"></label><label>Paste table, including its header<textarea id="reference-text" rows="7" placeholder="Year,Age,Tm,G,AB,H,HR,BA,OBP,SLG,OPS,OPS+,WAR" required></textarea></label><div class="import-action-row"><button class="primary">Preview table</button></div></form><div id="reference-preview" aria-live="polite"></div>`;
  fileBind('#reference-file','#reference-text','#reference-preview');resetPreview('#reference-form','#reference-preview');
  $('#reference-form').onsubmit=e=>{e.preventDefault();try{const [from,to]=years(),name=$('#reference-name').value.trim(),url=safeSourceURL($('#reference-url').value,'Baseball-Reference CSV'),label=$('#reference-title').value.trim();if(!name)throw Error('Enter a player name.');const parsed=parseReferenceTable($('#reference-text').value,$('#reference-aliases').value,from,to);const nc=parsed.headers.findIndex(h=>/^(name|player|player name)$/i.test(h));if(nc>=0)parsed.selected=parsed.selected.filter(i=>normalizedName(parsed.rows[i][nc].replace(/[\*#]+$/,''))===normalizedName(name));
  const scope=`${getTeam()[0]} · ${from}–${to} · codes ${$('#reference-aliases').value.trim()}`;
  $('#reference-preview').innerHTML=`<div class="notice"><strong>Review rows for ${esc(name)}</strong><p>Only checked rows will be saved. Values are preserved as provided, including WAR, OPS+, or ERA+ columns. The scoring assistant can fill statistical estimates; manual ratings and FLS points are preserved.</p></div>${parsed.warnings.map(w=>`<p class="error">${esc(w)}</p>`).join('')}<div class="import-action-row"><button type="button" class="subtle" id="select-matching">Select matching rows</button><button type="button" class="subtle" id="deselect-rows">Clear selection</button><span id="reference-count"></span></div>${tableHTML(parsed.headers,parsed.rows,esc,parsed.selected)}<button class="primary" id="apply-reference">Save selected rows</button>`;
  const count=()=>{const n=$$('[data-keep-row]:checked').length;$('#reference-count').textContent=`${n} of ${parsed.rows.length} rows selected`;$('#apply-reference').disabled=n===0;};count();$$('[data-keep-row]').forEach(x=>x.onchange=count);$('#select-matching').onclick=()=>{$$('[data-keep-row]').forEach(x=>x.checked=parsed.selected.includes(Number(x.dataset.keepRow)));count();};$('#deselect-rows').onclick=()=>{$$('[data-keep-row]').forEach(x=>x.checked=false);count();};
  $('#apply-reference').onclick=()=>{try{const rows=$$('[data-keep-row]:checked').map(x=>parsed.rows[Number(x.dataset.keepRow)]);if(!rows.length)throw Error('Select at least one row.');if(nc>=0&&rows.some(r=>normalizedName(r[nc].replace(/[\*#]+$/,''))!==normalizedName(name)))throw Error('A selected row belongs to a different player. Import one player’s stats at a time.');saveTables(name,[{id:crypto.randomUUID(),provider:'Baseball-Reference CSV',url,importedAt:new Date().toISOString(),label,scope,playerId:null,columns:parsed.headers,rows,summary:[]}]);}catch(err){toast(err.message);}};
  }catch(err){showError($('#reference-preview'),err);}};
 }
 function mlbView(config,prefill,current){
  $('#import-content').innerHTML=`<h3>Find a player. Bring in the numbers.</h3><p class="help">Search MLB’s stats service directly. Review the matching player, franchise seasons, and batting or pitching table before saving. These are MLB-sourced stats; Baseball-Reference metrics such as bWAR, OPS+, and ERA+ can be added through table import.</p><form id="mlb-form"><label>Player’s name<div class="mlb-search"><input id="mlb-name" value="${esc(prefill)}" placeholder="Try Paul O’Neill, Sandy Koufax…" required minlength="2" maxlength="100"><button class="primary">Search MLB</button></div></label></form><div id="mlb-results" aria-live="polite"></div><div id="mlb-selected"></div>`;
  let player=null,payload=null,request=0;
  $('#mlb-form').onsubmit=async e=>{e.preventDefault();const query=$('#mlb-name').value.trim();if(query.length<2)return;const mine=++request;$('#mlb-results').innerHTML='<p class="help">Searching MLB…</p>';$('#mlb-selected').innerHTML='';try{const data=await getJSON(`https://statsapi.mlb.com/api/v1/people/search?names=${encodeURIComponent(query)}&sportIds=1`);if(current!==generation||mine!==request||!$('#modal').open)return;const people=Array.isArray(data.people)?data.people.slice(0,30):[];$('#mlb-results').innerHTML=people.length?`<div class="mlb-result-list">${people.map((p,i)=>`<button class="mlb-result" data-pick-player="${i}"><span><strong>${esc(p.fullName)}</strong><small>${esc(p.primaryPosition?.name||'Player')} · ${p.birthDate?'Born '+esc(p.birthDate.slice(0,4)):'Birth year unavailable'} · MLB ID ${esc(p.id)}</small></span><span>Review stats ↗</span></button>`).join('')}</div>`:'<p class="notice">No matches returned. Try the full name or a different spelling. You can still import a Baseball-Reference table.</p>';
  $$('[data-pick-player]').forEach(btn=>btn.onclick=async()=>{player=people[Number(btn.dataset.pickPlayer)];const mine=++request;$('#mlb-selected').innerHTML='<p class="help">Loading franchise seasons…</p>';try{if(!Number.isInteger(player.id)||player.id<=0)throw Error('MLB returned an invalid player identifier.');const fetched=await getJSON(`https://statsapi.mlb.com/api/v1/people/${player.id}/stats?stats=yearByYear&group=hitting,pitching&sportIds=1`);if(current!==generation||mine!==request||!$('#modal').open)return;payload=fetched;renderPlayer();}catch(err){if(current===generation&&mine===request&&$('#mlb-selected'))showError($('#mlb-selected'),err);}});
  }catch(err){if(current===generation&&mine===request&&$('#mlb-results'))showError($('#mlb-results'),err);}};
  function renderPlayer(){
   $('#mlb-selected').innerHTML=`<div class="selected-player"><div><span class="eyebrow muted">PLAYER MATCH</span><h3>${esc(player.fullName)}</h3></div><span>${esc(player.primaryPosition?.name||'Player')}</span></div><form id="mlb-filter-form">${yearFields(config[2])}<label>Stats to import<select id="mlb-group"><option value="all">Batting and pitching, when available</option><option value="hitting">Batting only</option><option value="pitching">Pitching only</option></select></label><p class="help">${esc(getTeam()[1])} · MLB franchise team ${config[0]}. Set the season range to match your board’s era. Only returned MLB regular-season rows for this team are included; other teams and career totals are excluded.</p><button class="subtle">Update preview</button></form><div id="mlb-preview"></div>`;
   $('#mlb-filter-form').onsubmit=e=>{e.preventDefault();renderPreview();};$$('#mlb-filter-form input, #mlb-filter-form select').forEach(x=>x.oninput=()=>{$('#mlb-preview').innerHTML='<p class="help">Click Update preview to apply these filters.</p>';});renderPreview();
  }
  function renderPreview(){try{const [from,to]=years();const snapshots=mlbSnapshots(payload,player,getTeam()[0],from,to,$('#mlb-group').value);if(!snapshots.length){$('#mlb-preview').innerHTML='<p class="notice">No franchise seasons were returned for these filters. Try a different year range or use a Baseball-Reference table. Historical coverage can vary.</p>';return;}$('#mlb-preview').innerHTML=renderStatImports({statImports:snapshots},esc)+`<div class="notice">Save ${snapshots.length} ${snapshots.length===1?'table':'tables'} to ${esc(player.fullName)}. A matching candidate is updated; otherwise a new player is added. When enabled, the scoring assistant fills available statistical ratings. Manual ratings and FLS points are preserved.</div><button class="primary" id="apply-mlb">Save player data</button>`;$('#apply-mlb').onclick=()=>{try{saveTables(player.fullName,snapshots,player.primaryPosition?.name||'');}catch(err){toast(err.message);}};}catch(err){showError($('#mlb-preview'),err);}}
 }
 async function getJSON(url){try{const r=await fetch(url,{mode:'cors',credentials:'omit',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`MLB returned HTTP ${r.status}. Try again later or use table import.`);return await r.json();}catch(e){if(e.name==='TimeoutError'||e.name==='AbortError')throw Error('MLB took too long to respond. Try again or import a table.');if(e instanceof TypeError)throw Error('MLB could not be reached from this browser. Try again or use Baseball-Reference table import.');throw e;}}
 return {openImport};
}
