import {LEGACY_FACTORS,blankLegacy,calculateLegacy} from './legacy-score.js';
// Frozen editorial inputs before sensitivity calculation; not a fan survey or final ranking.
const hall=slug=>'https://baseballhall.org/hall-of-famers/'+slug;
const yn='https://www.mlb.com/yankees/history/retired-numbers';
export const PILOT_ROWS=[
 ['LAD','Vin Scully','Broadcaster',[10,10,10,10],'Longtime Dodgers voice and 1982 Ford C. Frick Award recipient.','https://baseballhall.org/discover-more/awards/frick/vin-scully','Generational voice; role excellence must stand on its own, without an N/A boost.'],
 ['LAD','Sandy Koufax','Player',[10,9.5,10,10],'Five straight NL ERA titles and three Cy Young Awards.',hall('koufax-sandy'),'A peak-dominance case; compare the quality of his identity evidence with other aces.'],
 ['LAD','Clayton Kershaw','Player',[10,9.5,9,10],'MVP and three-time Cy Young winner.','https://www.mlb.com/dodgers/video/kershaw-prospect-to-cy-young-c37188715','Modern-ace case; publicity must not substitute for evidence of lasting attachment.'],
 ['LAD','Pee Wee Reese','Player',[9.5,9,9,8.5],'Dodgers captain and leader of a seven-pennant team era.',hall('reese-pee-wee'),'Older-era case. Raised fan connection from the earlier illustrative 8.5 to 9 as a hypothesis after reviewing historical leadership evidence; still needs independent fan evidence.'],
 ['LAD','Kirk Gibson','Player',[7,9,10,6],'Walk-off homer in Game 1 of the 1988 World Series.','https://www.mlb.com/video/must-c-gibson-s-1988-ws-homer-c1864676883','Signature-moment case. The moment earns its strongest credit in signature legacy; it does not prove decades of identity or elite sustained production.'],
 ['LAD','Tommy Lasorda','Manager / coach',[10,9.5,9.5,9],'Managed two Dodgers World Series champions.',hall('lasorda-tommy'),'Manager case; evaluate managerial excellence rather than inventing playing stats.'],
 ['NYY','Babe Ruth','Player',[10,10,10,10],'His power helped transform baseball and the Yankees.',hall('ruth-babe'),'Foundational historical case; absence of living eyewitnesses must not reduce the rating.'],
 ['NYY','Derek Jeter','Player',[10,10,9.5,9],'Yankees captain with 3,465 hits.',hall('jeter-derek'),'Long-tenured modern icon; distinguish franchise symbolism from the breadth of playing excellence.'],
 ['NYY','Mariano Rivera','Player',[9.5,9.5,9.5,10],'Record-setting closer with exceptional postseason results.',hall('rivera-mariano'),'Reliever case. Role excellence can reach 10 without a starter’s workload.'],
 ['NYY','Don Mattingly','Player',[9.5,9.5,8.5,8.5],'Captain; nine Gold Gloves; 1985 MVP.',yn,'Beloved-player case; championships are not a prerequisite for fan connection.'],
 ['NYY','Billy Martin','Manager / coach',[9,8,9,8],'Yankees player and 1977 championship manager.',yn,'Polarizing-manager case. Being widely discussed is not the same thing as universal affection.'],
 ['NYY','Bucky Dent','Player',[7,8,9.5,5.5],'His 1978 tiebreaker home run remains a rivalry touchstone.','https://www.mlb.com/news/rewatch-bucky-dent-1978-game-163-home-run','Role-player case. Honor the signature memory without turning it into top-tier sustained excellence.'],
 ['PIT','Roberto Clemente','Player',[10,10,10,10],'3,000 hits, outstanding defense and humanitarian legacy.',hall('clemente-roberto'),'Foundational identity and cultural-impact case; use distinct explanations rather than repeating one honor four times.'],
 ['PIT','Honus Wagner','Player',[10,9,9.5,10],'Eight NL batting titles; Pirates tenure from 1900 through 1917.',hall('wagner-honus'),'Early-era case; fan connection is an explicit research uncertainty, not a penalty for playing before television.'],
 ['PIT','Willie Stargell','Player',[10,10,10,9],'Power hitter and leader of the 1979 champions.',hall('stargell-willie'),'Leadership and shared-era identity case; folklore should be supported beyond nostalgia alone.'],
 ['PIT','Bill Mazeroski','Player',[9.5,9.5,10,8],'1960 Series-ending home run and eight Gold Gloves.',hall('mazeroski-bill'),'Defense-plus-moment case; his excellence assessment must include his glove, not just batting.'],
 ['PIT','Tony Peña','Player',[7.5,8,7.5,8],'Distinctive catching stance; three Gold Gloves with Pittsburgh.','https://en.wikipedia.org/wiki/Tony_Pe%C3%B1a','Personal-favorite control. Joe’s affection earns no extra points. This secondary source and fan-connection estimate need stronger research.'],
 ['PIT','Steve Blass','Broadcaster',[9,9,9,8],'1971 Series hero and longtime Pirates broadcaster.','https://en.wikipedia.org/wiki/Steve_Blass','Multiple-role case. For this test excellence assesses broadcasting; pitching contributes historical context. No two separate excellence bonuses. Secondary source needs corroboration.']
].map(([team,name,type,ratings,fact,source,note])=>({team,name,type,ratings,fact,source,note}));
const REASONS={
 'Vin Scully':['The defining team voice is the identity hypothesis.','Generational affection is plausible but not quantified here.','The calls form a lasting franchise soundtrack.','Broadcasting craft and professional recognition support the ceiling.'],
 'Sandy Koufax':['A defining franchise ace rather than merely a visiting star.','Enduring attachment is inferred; fan evidence remains incomplete.','The peak and its remembered stories support a defining signature.','Exceptional peak excellence offsets a shorter playing career.'],
 'Clayton Kershaw':['The modern franchise-ace identity supports the ceiling.','Current affection needs a historical perspective before finalizing.','Major signature legacy, with room for debate against older icons.','The pitching record supports a historic-excellence hypothesis.'],
 'Pee Wee Reese':['Captaincy supports central franchise identity.','Historical leadership suggests attachment; independent fan evidence is still needed.','Leadership and influence matter beyond one highlight.','Strong sustained shortstop contribution, below the absolute excellence ceiling.'],
 'Kirk Gibson':['A defining chapter can matter without defining the entire franchise.','The connection estimate needs evidence beyond replay frequency.','A single unforgettable moment can justify the signature ceiling.','The excellence estimate considers the limited franchise body of work.'],
 'Tommy Lasorda':['The hypothesis is inseparability from the team identity.','Visible personality is not sufficient proof of affection; review required.','A managerial persona and era can create lasting lore.','Evaluate results and leadership against other managers.'],
 'Babe Ruth':['Foundational franchise symbolism supports the ceiling hypothesis.','Historical attachment must count even without living eyewitnesses.','His influence supports a defining-signature assessment.','Evaluate Yankees production, excluding Boston pitching achievements.'],
 'Derek Jeter':['A captain can become a franchise symbol.','Generational connection is a hypothesis needing fan evidence.','A broad signature legacy need not score a perfect ten.','Outstanding full-career contribution with room below the ceiling.'],
 'Mariano Rivera':['A central franchise figure without requiring an automatic ten.','The affection rating remains an editorial judgment.','A recognizable style of excellence can become franchise lore.','A reliever can reach the role-excellence ceiling without starter innings.'],
 'Don Mattingly':['Central era identity does not require a championship.','The attachment hypothesis is high but not measured here.','Lasting symbolism can matter without a championship highlight.','Assess peak and sustained quality without a ring requirement.'],
 'Billy Martin':['Repeated franchise association supports strong identity.','Polarization means notoriety must not be treated as universal affection.','A distinctive managerial story can create substantial lore.','Evaluate management within its role, without doubling playing credit.'],
 'Bucky Dent':['A memorable chapter is narrower than foundational identity.','Rivalry memory is a starting point, not a fan survey.','The signature event earns most of its credit here.','The excellence estimate must reflect the broader playing contribution.'],
 'Roberto Clemente':['Franchise and personal identity appear exceptionally intertwined.','The ceiling remains an editorial attachment hypothesis.','Cultural influence and baseball memory support a defining legacy.','Assess the full playing contribution, including defense.'],
 'Honus Wagner':['An early foundational identity must count fully.','Nine is a research hypothesis, not an age penalty.','Lasting historical influence can substitute for modern highlight footage.','Role and era context support a historic-excellence ceiling.'],
 'Willie Stargell':['Leadership can embody franchise identity.','Shared-era affection is inferred and still needs fan evidence.','A collective team story can support the signature ceiling.','Outstanding contribution need not equal the greatest possible performance.'],
 'Bill Mazeroski':['A durable franchise association supports high identity.','Attachment needs independent evidence beyond the famous replay.','An unforgettable moment supports a maximum signature rating.','Defense must be included when judging playing excellence.'],
 'Tony Peña':['Strong era association without assuming universal franchise symbolism.','Joe’s personal favorite status adds no points to this hypothesis.','A distinctive playing style can generate lore without a title moment.','Catching defense belongs in the excellence assessment.'],
 'Steve Blass':['Multiple roles may deepen one franchise identity.','The fan-connection hypothesis needs stronger corroboration.','The combined story matters without adding a second score.','For this pilot the excellence role is broadcaster; it needs better evidence.']
};
export function pilotCandidate(row){const legacy=blankLegacy();LEGACY_FACTORS.forEach(([k],i)=>{legacy.ratings[k]=row.ratings[i];legacy.evidence[k]={reason:'Editorial pilot estimate: '+REASONS[row.name][i]+' Historical source supplies context; the numerical judgment needs review.',source:row.source,confidence:k==='connection'?'low':'medium'};});return {name:row.name,type:row.type,legacy};}
export function pilotAnalysis(){
 const base=[30,25,25,20],variants=[{name:'Default',weights:base}];
 for(let from=0;from<4;from++)for(let to=0;to<4;to++)if(from!==to){const weights=[...base];weights[from]-=5;weights[to]+=5;variants.push({name:`Move 5 points: ${LEGACY_FACTORS[from][1]} → ${LEGACY_FACTORS[to][1]}`,weights});}
 const score=(r,w)=>calculateLegacy(pilotCandidate(r),w).value;
 const results=PILOT_ROWS.map(r=>{const scores=variants.map(v=>score(r,v.weights));return {...r,score:scores[0],minimum:Math.min(...scores),maximum:Math.max(...scores)};});
 const pairs=[];for(const team of ['LAD','NYY','PIT']){const rows=PILOT_ROWS.filter(r=>r.team===team);for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j],initial=score(a,base)-score(b,base);const changed=variants.slice(1).filter(v=>{const gap=score(a,v.weights)-score(b,v.weights);return Math.sign(gap)!==Math.sign(initial);});if(changed.length)pairs.push({team,a:a.name,b:b.name,variants:changed.map(v=>v.name)});}}
 return {variants,results,pairs};
}
