import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import worker from '../dist/server/index.js';
import {rankedCandidates} from '../public/workspace-extra.js';
import {seedState,newCandidate,validateImport} from '../public/model.js';
import {catalogFromSplits} from '../server/catalog.js';
import {candidateSuggestions,acceptDiscovered,discoveryKey} from '../public/research-model.js';
import {effectiveScope} from '../public/franchise-scope.js';
import {rosterChecks,rosterNextStep} from '../public/roster-rules.js';import {SLOTS,newRoster} from '../public/legends.js';
function environment(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const data=new Map();return {DB:{prepare(q){return {bind(...values){const stmt=sql.prepare(q);return {first:async()=>stmt.get(...values)||null,all:async()=>({results:stmt.all(...values)}),run:async()=>({meta:{changes:Number(stmt.run(...values).changes)}})};}}; }},BUCKET:{put:async(k,v,meta)=>data.set(k,{v,meta}),delete:async k=>data.delete(k),get:async k=>data.has(k)?{json:async()=>JSON.parse(data.get(k).v),body:data.get(k).v,httpMetadata:data.get(k).meta?.httpMetadata}:null}};}
const request=(path,method='GET',body,user='owner',origin='https://studio.example')=>new Request('https://studio.example'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('worker accepts current Sites identity headers, enforces same origin, and persists with optimistic concurrency',async()=>{const env=environment();assert.equal((await worker.fetch(request('/', 'GET',null,null),env)).status,401);const emailRequest=new Request('https://studio.example/',{headers:{'oai-authenticated-user-email':'owner@example.com'}});assert.equal((await worker.fetch(emailRequest,env)).status,200);const before=await worker.fetch(request('/api/workspace'),env);assert.deepEqual(await before.json(),{revision:0,state:null});const state=seedState();assert.equal((await worker.fetch(request('/api/workspace','PUT',{revision:0,state},'owner','https://foreign.example'),env)).status,403);assert.equal((await worker.fetch(request('/api/workspace','PUT',{revision:0,state}),env)).status,200);const a=structuredClone(state);a.boards.LAD.notes='device A';const b=structuredClone(state);b.boards.LAD.notes='device B';const writes=await Promise.all([worker.fetch(request('/api/workspace','PUT',{revision:1,state:a}),env),worker.fetch(request('/api/workspace','PUT',{revision:1,state:b}),env)]);assert.deepEqual(writes.map(x=>x.status).sort(),[200,409]);const saved=await (await worker.fetch(request('/api/workspace'),env)).json();assert.equal(saved.revision,2);assert.equal(saved.state.boards.LAD.notes,'device A');assert.equal((await (await worker.fetch(request('/api/workspace','GET',null,'someone-else'),env)).json()).state,null);});
test('edition snapshots are immutable, owner scoped and remain independent of working state',async()=>{const env=environment(),state=seedState();const r=await worker.fetch(request('/api/editions','POST',{state,team:'LAD',title:'First edition'}),env);assert.equal(r.status,201);const saved=await r.json();state.boards.LAD.notes='Edited later';await worker.fetch(request('/api/workspace','PUT',{revision:0,state}),env);const old=await (await worker.fetch(request('/api/editions/'+saved.id),env)).json();assert.notEqual(old.state.boards.LAD.notes,state.boards.LAD.notes);assert.equal((await worker.fetch(request('/api/editions/'+saved.id,'GET',null,'other'),env)).status,404);assert.equal((await worker.fetch(request('/api/editions/'+saved.id,'PUT',{state}),env)).status,404);});
test('discovery uses franchise years, excludes foreign teams, deduplicates seasons and respects target',()=>{const row=(id,year,team=119)=>({player:{id,fullName:'Player '+id},team:{id:team},season:String(year),position:{abbreviation:'SS'},stat:{hits:100,plateAppearances:400,homeRuns:12,gamesPlayed:130,ops:'.800'}});const rows=Array.from({length:210},(_,i)=>row(i+1,2000));rows.push(row(1000,1950),row(1001,2000,147),rows[0]);const found=catalogFromSplits(rows,[],119,1990,2010,175);assert.equal(found.length,175);assert.equal(found.find(x=>x.mlbId===1).summary.H,100);assert.ok(!found.some(x=>x.mlbId>=1000));assert.equal(new Set(found.map(x=>x.mlbId)).size,175);});
test('suggestion acceptance is deliberate, repeated discovery preserves exclusions, scores and order',()=>{const b=seedState().boards.LAD,original=b.candidates.map(x=>x.id),p={name:'A New Player',mlbId:123456,role:'SS',era:'1970–1980',whyAdded:'Franchise appearances'};assert.equal(candidateSuggestions(b,[p]).length,1);assert.deepEqual(b.candidates.map(x=>x.id),original);assert.equal(acceptDiscovered(b,p),true);assert.deepEqual(rankedCandidates(b).map(x=>x.id),original);assert.equal(acceptDiscovered(b,p),false);assert.equal(b.candidates.at(-1).legacy.ratings.identity,null);assert.deepEqual(b.candidates.slice(0,-1).map(x=>x.id),original);const q={...p,mlbId:999999,name:'Excluded Player'};b.studio.exclusions.push(discoveryKey(q));assert.equal(candidateSuggestions(b,[q]).length,0);});
test('roster enforces 13 pitchers, bullpen roles, lefty specialist and qualified two-way exemption',()=>{const benchRole={C2:'Catcher',UTIL:'2B / SS',OF4:'Center field',CI:'1B / 3B',PH:'Left field'},cs=SLOTS.map(([slot],i)=>{const c=newCandidate('Player '+i),starter=slot.startsWith('SP'),reliever=['CL','SU1','SU2','MR1','MR2','LHS','LR'].includes(slot);c.role=starter?'Starting pitcher':reliever?'Relief pitcher':benchRole[slot]||slot;c.profile.throws=slot==='LHS'?'L':'';c.profile.advancedStats={franchiseSeasons:4,PA:starter||reliever?0:1200,IP:starter?400:reliever?150:0,startIP:starter?400:0,reliefIP:reliever?150:0};return c;}),r=newRoster();SLOTS.forEach(([k],i)=>r.slots[k]=cs[i].id);assert.equal(rosterChecks(r,cs).pitchers,12);assert.equal(rosterChecks(r,cs).complete,true);cs[0].profile.designation='two-way';assert.equal(rosterChecks(r,cs).pitchers,13);assert.equal(rosterChecks(r,cs).complete,true);cs[1].profile.designation='two-way';assert.equal(rosterChecks(r,cs).valid,false);assert.equal(rosterChecks(r,cs).pitchers,14);cs[1].profile.twoWayQualified=true;assert.equal(rosterChecks(r,cs).pitchers,13);cs[SLOTS.findIndex(([k])=>k==='LHS')].profile.throws='R';assert.match(rosterChecks(r,cs).errors.join(' '),/left-handed/);});
test('guided roster reports one next action at a time',()=>{const r=newRoster(),c=newCandidate('Eligible catcher');c.role='Catcher';c.profile.advancedStats={franchiseSeasons:4,PA:900};assert.deepEqual(rosterNextStep(r,[c]),{state:'build',slot:'C',text:'Fill Catcher next.'});r.slots.C=c.id;assert.equal(rosterNextStep(r,[c]).slot,'1B');});
test('historical scope and optional research survive backups; unsafe source schemes are rejected',()=>{const state=seedState();assert.equal(effectiveScope('ATH',state.boards.ATH.studio).from,1968);assert.equal(effectiveScope('WSH',{scopeKey:'expos'}).to,2004);state.boards.LAD.studio.suggested=[{name:'Candidate',mlbId:12}];state.boards.LAD.studio.jobs.stats={ids:['a','b'],cursor:1,review:[]};const restored=validateImport(state).state;assert.equal(restored.boards.LAD.studio.jobs.stats.cursor,1);state.boards.LAD.candidates[0].profile.research={title:'Bad',extract:'x',checkedAt:'2026-09-09',source:'javascript:alert(1)'};assert.throws(()=>validateImport(state),/source/);});
test('cloud migration uploads old browser data once and preserves a conflicting device draft for recovery',async()=>{const {createCloudSave}=await import('../public/cloud-save.js');const store=new Map(),env=environment(),oldFetch=globalThis.fetch,oldWindow=globalThis.window,oldStorage=globalThis.localStorage;globalThis.window={addEventListener(){}};globalThis.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};globalThis.fetch=(path,options={})=>worker.fetch(new Request('https://studio.example'+path,{...options,headers:{...options.headers,'oai-authenticated-user-id':'owner',Origin:'https://studio.example'}}),env);try{let state=seedState();state.boards.LAD.notes='Old browser notes';const cloud=createCloudSave({getState:()=>state});state=await cloud.start(state);assert.equal(cloud.revision,1);const key='legacy-lore-studio-v1-draft';const stale=structuredClone(state);stale.boards.LAD.notes='Unsynced device';store.set(key,JSON.stringify({revision:0,dirty:true,state:stale}));const next=createCloudSave({getState:()=>state});const result=await next.start(seedState());assert.equal(result.boards.LAD.notes,'Old browser notes');assert.equal(JSON.parse(store.get(next.recoveryKey)).boards.LAD.notes,'Unsynced device');assert.match(next.status,/recovery/);}finally{globalThis.fetch=oldFetch;globalThis.window=oldWindow;globalThis.localStorage=oldStorage;}});
test('honors timeline excludes other teams, minor leagues, duplicate records and out-of-scope years',async()=>{const {franchiseHonors}=await import('../public/honors.js');const award={id:'NL_MVP',name:'NL MVP',date:'2014-11-13',season:'2014',team:{id:119}};const result=franchiseHonors({awards:[award,award,{...award,id:'other',team:{id:147}},{...award,id:'minor',team:{id:456}},{...award,id:'older',season:'2005'}]},'LAD',2010,2020);assert.equal(result.length,1);assert.equal(result[0].name,'NL MVP');});
