import test from 'node:test';import assert from 'node:assert/strict';
import {seedState,newCandidate,validateImport} from '../public/model.js';
import {previewAutoRanking,applyRankingPreview} from '../public/auto-ranking.js';
const player=(name,performance,peak,longevity)=>{const c=newCandidate(name);Object.assign(c.scores,{performance,peak,longevity});Object.assign(c.legacy.ratings,{identity:performance,connection:peak,signature:peak,excellence:longevity});for(const e of Object.values(c.legacy.evidence))Object.assign(e,{reason:'Test assessment',source:'https://example.org/test',confidence:'medium'});c.profile.pool=true;return c;};
const apex=(name,value)=>{const c=newCandidate(name);c.profile.pool=true;c.profile.advancedStats={found:true,version:'role-lane-v3',role:'BAT',totalWAR:value,batWAR:value,pitchWAR:0,peak5WAR:value/2,WAA:value/2,REP:value/2,Apex:value/3,Prime:value/2,Reign:value,APEX_R:value,APEX_100:value,PA:6000,IP:0,seasons:10,source:'https://www.baseball-reference.com/data/'};return c;};
test('APEX is the default, preserves ties and leaves custom blanks unscored',()=>{const b=seedState().boards.LAD;b.candidates=[apex('Lower',40),apex('High',90),apex('Tie',90),newCandidate('Missing'),newCandidate('Voice','Broadcaster')];const before=JSON.stringify(b);const p=previewAutoRanking(b,'LAD',{lens:'apex',useLore:false});assert.equal(JSON.stringify(b),before);assert.equal(p.eligible,3);assert.deepEqual(p.rows.slice(0,3).map(r=>r.candidate.name),['High','Tie','Lower']);assert.equal(p.rows[0].value,90);assert.equal(p.rows.at(-1).value,null);assert.equal(p.candidates.find(c=>c.name==='Missing').legacy.ratings.connection,null);assert.equal(p.top.length,5);});
test('pilot fills only untouched blank lore inputs, honors custom scopes and preserves FLS and manual evidence',()=>{const b=seedState().boards.LAD;const c=newCandidate('Sandy Koufax');c.fls.p1=177;c.legacy.ratings.identity=7;c.legacy.evidence.connection.reason='My research in progress';b.candidates=[c];const p=previewAutoRanking(b,'LAD',{lens:'legacy'});assert.equal(p.candidates[0].legacy.ratings.identity,7);assert.equal(p.candidates[0].legacy.ratings.connection,null);assert.equal(p.candidates[0].legacy.evidence.connection.reason,'My research in progress');assert.equal(p.candidates[0].fls.p1,177);assert.equal(p.loreFilled,2);assert.equal(p.eligible,0);b.studio.from=1958;const custom=previewAutoRanking(b,'LAD',{lens:'legacy'});assert.equal(custom.loreFilled,0);});
test('at most 200 previously unranked candidates are promoted, and backup restores the generated order',()=>{const state=seedState(),b=state.boards.LAD;b.candidates=Array.from({length:240},(_,i)=>apex('Player '+i,(i%10)+1));const p=previewAutoRanking(b,'LAD',{lens:'apex',useLore:false});assert.equal(p.top.length,200);applyRankingPreview(b,p);assert.equal(b.candidates.filter(c=>!c.profile.pool).length,200);assert.equal(b.candidates.filter(c=>c.profile.pool).length,40);const restored=validateImport(state).state.boards.LAD;assert.deepEqual(restored.candidates.map(c=>c.id),b.candidates.map(c=>c.id));assert.equal(restored.studio.lastAutoRanking.lens,'apex');});
test('missing APEX data never fabricates a performance score',()=>{const b=seedState().boards.LAD;const unknown=newCandidate('Historical legend'),lower=apex('Assessed incumbent',50),higher=apex('New researched candidate',90);lower.profile.pool=false;b.candidates=[unknown,lower,higher];const p=previewAutoRanking(b,'LAD',{lens:'apex',useLore:false});assert.equal(p.rows.find(r=>r.candidate.name==='Historical legend').value,null);assert.equal(p.top[0].name,'New researched candidate');assert.equal(p.top[1].name,'Assessed incumbent');});
